# Use the official Node.js image as the base image
FROM node:22-alpine

# Set the working directory
WORKDIR /home/node/app

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies & dev dependencies
ENV NODE_ENV=development
RUN npm install

# Start the React development server
CMD ["npm", "run", "start"]
