# Use the official Node.js image as the base image
FROM node:alpine

# Set the working directory
WORKDIR /home/node/app

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Start the React development server
CMD ["npm", "run", "start"]
