services:
  db:
    ports:
      - ${DB_PORT}:${DB_PORT} # dev

  client:
    build: 
      dockerfile: Dockerfile.dev # dev
    environment:
      - REACT_APP_BACKEND_URL=localhost:${SERVER_PORT}
    ports: !override
      - ${CLIENT_PORT}:3000 # dev. in prod, should be 3000:80
  
  server:
    environment:
      - IS_DEV=true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT} # dev
    volumes:
      - ./server:/usr/src/app # dev

  tts:
    ports:
      - ${TTS_PORT}:${TTS_PORT} # dev

  llm:
    ports:
      - ${LLM_PORT}:${LLM_PORT}
